[package]
name = "gift_cards"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework-latest" }

[addresses]
gift_cards = "0x0"